import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'


import { useScrollPosition } from "../hooks/useScrollPosition"


export default function Home() {

  const scrollPosition = useScrollPosition()

  console.log(scrollPosition)

  function classNames(...classes: (string | undefined | null)[]): string {
    return classes.filter(Boolean).join(' ');
  }

  return (
    <>

    <Head>
      <title>Super Manifold</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>



    {/* `fixed w-full bg-black`   */}
    <header className={classNames(scrollPosition > 0 ? '' : '', 'fixed', 'w-full', 'transition-colors')}>
      <nav className="">
        <div className="container mx-auto ">
          <div className="py-4 flex items-center">
            
            <div className="flex-auto">
              <Link href="/">
                <Image 
                  alt="Super Manifold Logo"
                  src="/logo/230217_SuperManifold-white.svg" 
                  height={36} 
                  width={243} 
                />  
              </Link>
            </div>

            <div className="flex-initial">
              <ul className="flex text-white">
                <Link href="/"><li className="ml-12">D1</li></Link>
                <Link href="/"><li className="ml-12">Waitlist</li></Link>
                <Link href="/"><li className="ml-12">About</li></Link>
              </ul>
            </div>

          </div>
        </div>
      </nav>
    </header>

    <main>
    <div>
      <Image
        alt="Super Manifold B1-H"
        src="/temp/230212_init_cc japaneseKerning.jpg"
        width={5120}
        height={2880}
        sizes="100vw"
        style={{
          width: '100%',
          height: 'auto',
        }}
      />
    </div>
    <div>
      <Image
        alt="Super Manifold B1-H"
        src="/temp/230212_init_cc japaneseKerning.jpg"
        width={5120}
        height={2880}
        sizes="100vw"
        style={{
          width: '100%',
          height: 'auto',
        }}
      />
    </div>
    <div>
      <Image
        alt="Super Manifold B1-H"
        src="/temp/230212_init_cc japaneseKerning.jpg"
        width={5120}
        height={2880}
        sizes="100vw"
        style={{
          width: '100%',
          height: 'auto',
        }}
      />
    </div>
    </main>



    </>
  )


}



// fill
// sizes="100vw"
// style={{
//   objectFit: 'cover',
// }}